# -*- coding: utf-8 -*-
"""fft

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UkdGCa_UIAkgxAhc-5yn4zYuBa_q9gCk
"""

def fft_radix2(x):
    x = np.asarray(x, dtype=complex)
    N = len(x)

    if N == 0 or (N & (N - 1)) != 0:
        raise ValueError(
            "O comprimento precisa ser uma potência de 2."
        )

    bits = N.bit_length() - 1
    indices = np.zeros(N, dtype=int)

    for i in range(N):
        valor = i
        reverso = 0

        for _ in range(bits):
            reverso = (reverso << 1) | (valor & 1)
            valor >>= 1

        indices[i] = reverso

    a = x[indices].copy()

    tamanho = 2

    while tamanho <= N:
        metade = tamanho // 2

        fatores = np.exp(
            -2j * np.pi * np.arange(metade) / tamanho
        )

        for inicio in range(0, N, tamanho):
            par = a[inicio:inicio + metade].copy()

            impar = (
                a[inicio + metade:inicio + tamanho].copy()
                * fatores
            )

            a[inicio:inicio + metade] = par + impar
            a[inicio + metade:inicio + tamanho] = par - impar

        tamanho *= 2

    return a


def ifft_radix2(X):
    X = np.asarray(X, dtype=complex)

    return np.conj(fft_radix2(np.conj(X))) / len(X)


rng = np.random.default_rng(123)

x = rng.normal(size=16) + 1j * rng.normal(size=16)

X_dft = dft(x)
X_fft = fft_radix2(x)

x_recuperado = ifft_radix2(X_fft)

print("Erro máximo DFT versus FFT:",
      np.max(np.abs(X_dft - X_fft)))

print("Erro máximo da reconstrução:",
      np.max(np.abs(x - x_recuperado)))

print("FFT igual à DFT:",
      np.allclose(X_dft, X_fft, atol=1e-10))




def medir_tempo(funcao, x, repeticoes=3):
    tempos = []

    for _ in range(repeticoes):
        inicio = time.perf_counter()
        funcao(x)
        fim = time.perf_counter()

        tempos.append(fim - inicio)

    return float(np.median(tempos))


rng = np.random.default_rng(2026)

tamanhos = [16, 32, 64, 128, 256]
resultados_tempo = []

for N in tamanhos:
    x = rng.normal(size=N) + 1j * rng.normal(size=N)

    tempo_dft = medir_tempo(dft, x, repeticoes=3)
    tempo_fft = medir_tempo(fft_radix2, x, repeticoes=5)

    erro = np.max(np.abs(dft(x) - fft_radix2(x)))

    resultados_tempo.append({
        "N": N,
        "DFT (s)": tempo_dft,
        "FFT (s)": tempo_fft,
        "Razão DFT/FFT": tempo_dft / tempo_fft,
        "Erro máximo": erro
    })

tabela = pd.DataFrame(resultados_tempo)
display(tabela)

plt.figure(figsize=(8, 5))

plt.plot(
    tabela["N"],
    tabela["DFT (s)"],
    "o-",
    label="DFT manual"
)

plt.plot(
    tabela["N"],
    tabela["FFT (s)"],
    "s-",
    label="FFT radix-2 manual"
)

plt.yscale("log")
plt.xlabel("Número de amostras N")
plt.ylabel("Tempo de execução (segundos)")
plt.title("Comparação de desempenho: DFT e FFT")
plt.grid(True, which="both")
plt.legend()
plt.show()