# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UkdGCa_UIAkgxAhc-5yn4zYuBa_q9gCk
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Configuração de exibição do NumPy e Pandas
np.set_printoptions(precision=4, suppress=True)
pd.options.display.float_format = '{:.2e}'.format


def dft(x):
    """Calcula a DFT de forma vetorizada usando a matriz de Fourier."""
    x = np.asarray(x, dtype=complex)
    N = len(x)
    n = np.arange(N)
    k = n.reshape((N, 1))

    # Matriz de Fourier W[k, n] = exp(-2j * pi * k * n / N)
    W = np.exp(-2j * np.pi * k * n / N)
    return np.dot(W, x)


def idft(X):
    """Calcula a IDFT de forma vetorizada."""
    X = np.asarray(X, dtype=complex)
    N = len(X)
    n = np.arange(N)
    k = n.reshape((N, 1))

    # Matriz da IDFT W_inv[n, k] = exp(2j * pi * k * n / N) / N
    W_inv = np.exp(2j * np.pi * k * n / N) / N
    return np.dot(W_inv, X)


# --- 1. Teste Básico da DFT e IDFT ---
x_teste = np.array([1, 2, 3, 4], dtype=float)
X_teste = dft(x_teste)
x_recuperado = idft(X_teste)

print("--- Teste Básico ---")
print("Sinal original:   ", x_teste)
print("DFT:              ", X_teste)
print("Sinal recuperado: ", np.real_if_close(x_recuperado))
print(f"Erro máximo:      {np.max(np.abs(x_teste - x_recuperado)):.2e}\n")


# --- 2. Validação das Propriedades da DFT ---
rng = np.random.default_rng(7)
N = 8
x = rng.normal(size=N) + 1j * rng.normal(size=N)
y = rng.normal(size=N) + 1j * rng.normal(size=N)

a, b, m = 2.0, -0.5, 2
X = dft(x)
Y = dft(y)

# 1. Linearidade
erro_linearidade = np.max(np.abs(dft(a*x + b*y) - (a*X + b*Y)))

# 2. Deslocamento circular
x_deslocado = np.roll(x, m)
X_teorico = X * np.exp(-2j * np.pi * np.arange(N) * m / N)
erro_deslocamento = np.max(np.abs(dft(x_deslocado) - X_teorico))

# 3. Conjugação
indices = (-np.arange(N)) % N
erro_conjugacao = np.max(np.abs(dft(np.conj(x)) - np.conj(X[indices])))

# 4. Teorema de Parseval
energia_tempo = np.sum(np.abs(x)**2)
energia_frequencia = np.sum(np.abs(X)**2) / N
erro_parseval = abs(energia_tempo - energia_frequencia)

# 5. Reconstrução pela IDFT
erro_idft = np.max(np.abs(idft(X) - x))

# Consolidação dos resultados em DataFrame
resultados = pd.DataFrame({
    "Propriedade": [
        "Linearidade",
        "Deslocamento circular",
        "Conjugação",
        "Parseval",
        "DFT seguida de IDFT"
    ],
    "Erro Máximo": [
        erro_linearidade,
        erro_deslocamento,
        erro_conjugacao,
        erro_parseval,
        erro_idft
    ]
})

print("--- Validação de Propriedades ---")
display(resultados)


# --- 3. Visualização Gráfica (Aproveitando o Matplotlib) ---
plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.stem(np.arange(N), np.abs(x), basefmt="k-")
plt.title("Magnitude do Sinal no Tempo |x[n]|")
plt.xlabel("n")
plt.grid(True)

plt.subplot(1, 2, 2)
plt.stem(np.arange(N), np.abs(X), basefmt="k-")
plt.title("Espectro de Magnitude |X[k]|")
plt.xlabel("k")
plt.grid(True)

plt.tight_layout()
plt.show()